### ISSUE TITLE
Property sort order recess / smacss/ concentric doesn't work 

### ISSUE THREAD

**Issue by bdiekert** [srowhani/sass-lint-auto-fix#10]
## Problem Description

Property resolves alphabetically, but not in other orders like recess, smacss or concentric. 

They're hints in the code, but it seems that the yaml files are missing.

## Steps to recreate

* Put `sass-lint.yml` at the root of the project with following content:
```
resolvers:
  property-sort-order:
    - 1
    - order: concentric
```
* Run `sass-lint-auto-fix -c sass-lint.yml`
* Property sort is alphabetically

**Comment by srowhani** [comment]
This appears to be an issue with documentation. As it is currently when resolving files, the context for the rules given to the rule resolver will come from sass-lint.

By default, sass-lint will look for a `.sass-lint.yml` or `.sasslintrc` in the root.
https://github.com/sasstools/sass-lint/blob/develop/lib/config.js#L54

So in your case, for your project you would add a `.sass-lint.yml` in the root of your project with:

```yml
rules:
  property-sort-order:
    - 1
    - order: concentric
```

The config file specified when running `sass-lint-auto-fix` is to enable or disable rule resolvers - if you only wish to apply certain types of fixes. Documentation regarding the topic, and include CLI flag to specify custom sass-lint config should be added.
