### ISSUE TITLE
Issue with .sass-lint.yml path

### ISSUE THREAD

**Issue by OBats** [srowhani/sass-lint-auto-fix#140]
## Problem Description
When I running `npm run lint:fix` sass-lint-auto-fix runs only in one file, but not of all scss files mentioned in my `.sass-lint.yml` config

[sass-lint-auto-fix result](https://monosnap.com/direct/RU6IpNOdFzut25tTtaNdmdAwWFVuXS)

My `.sass-lint.yml` config:
```
options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1`
  ...
```

[my folder structure](https://take.ms/n4zjH)

`lint:fix` script: `"lint:fix": "sass-lint-auto-fix"`

`sass-lint-auto-fix` version: 0.19.0

The explicit also doesn`t work (same result):
"sass-lint-auto-fix --config-sass-lint .sass-lint.yml"

How I can use `sass-lint-auto-fix`to validate and fix (if necessary) **all** my `.scss` files according to sass-lint rules in `.sass-lint.yml` config?

Thank you :)
