### ISSUE TITLE
indentation is not auto fixed 

### ISSUE THREAD

**Issue by BezMaster** [srowhani/sass-lint-auto-fix#18]
## Problem Description

I am searching a solution to fix bad indentation in my scss files and i thought that sass-lint-auto-fix was made for that. But it does not work and i dont understand. Could you confim me that your lib can do indentation fix auto ?

Thanks

Put into words briefly what you have encountered

## Screenshot

Helps to recreate the issue

## Steps to recreate

- List
- of
- steps
- to
- recreate

**Comment by srowhani** [comment]
Implementing new rule resolvers are a work in progress, and over time more will be added. Resolving indentation issues is definitely on the roadmap, and will for sure be added in future iterations.

**Comment by BezMaster** [comment]
Thx a lot i'll try that tomorrow ;)

**Comment by srowhani** [comment]
Yes!

The correct syntax in the `.sass-lint.yml` would be:
```yml
...
indentation: 
  - 1
  - size: 4
```

**Comment by BezMaster** [comment]
Thx a lot, it works fine

**Comment by DanFerro** [comment]
I'm seeing an issue with spaces here.

```
  indentation:
    - 2
    - size: 2
```

**Comment by srowhani** [comment]
Would you be able to prepare a sample file or project for context

**Comment by DanFerro** [comment]
[_normalize.scss.zip](https://github.com/srowhani/sass-lint-auto-fix/files/2088397/_normalize.scss.zip)

**Comment by srowhani** [comment]
@DanFerro Could you include your sass-lint-auto-fix configuration file as well. I've tried it, and it seems to be working.

#### Output
```sh
[~/Desktop]$ sass-lint-auto-fix -c "./default.yml" ./_normalize.scss
@config    Setting up sentry
@fix       Running resolver indentation on ./_normalize.scss
@write     Writing resolved tree to ./_normalize.scss
```

#### default.yml
```yml
resolvers:
  indentation:
    - 1
    - size: 2
```

**Comment by DanFerro** [comment]
```
files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  empty-line-between-blocks: 1
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 2
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-extends: 1
  no-ids: 1
  no-trailing-whitespace: 1
  no-qualifying-elements: 0
  one-declaration-per-line: 1
  single-line-per-selector: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  trailing-semicolon: 1
  variable-name-format: 1
```
