### ISSUE TITLE
Cannot read property 'is' of undefined - final-newline.js:40:15

### ISSUE THREAD

**Issue by sidouglas** [srowhani/sass-lint-auto-fix#26]
## Problem Description

I ran this command when I installed your package globally.

```
sass-lint-auto-fix -c .sass-lint.yml
```

![__documents_nrl_working_source_nrl_web_client_ _nrldigital_nrls-macbook-pro-2_ _-zsh_ _139x43](https://user-images.githubusercontent.com/1107946/40456991-827a3d54-5f37-11e8-9df4-dceeaead6821.png)

My .sass-lint.yml file
```
files:
    include: 'src/styles/**/*.scss'
    ignore:
        - 'src/styles/ui-framework/mixins/_generate-utils.scss'
        - 'src/styles/ui-framework/utils/_u-spacing.scss'

rules:
    border-zero:
        - 1
        - convention: none

    brace-style:
        - 1
        - style: 'stroustrup'

    class-name-format:
        - 1
        - convention: hyphenatedbem

    empty-line-between-blocks: 1

    extends-before-mixins: 1

    extends-before-declarations: 1

    force-element-nesting: 0

    force-pseudo-nesting: 0

    indentation:
        - 1
        - size: 2

    leading-zero:
        - 0
        - include: false

    mixins-before-declarations:
        - 1
        - exclude: ['media-query', 'mq']

    nesting-depth:
        - 0
        - max-depth: 3

    no-color-keywords: 0

    no-color-literals: 0

    no-important: 0

    no-mergeable-selectors: 0

    no-trailing-zero: 0

    no-transition-all: 0

    no-vendor-prefixes: 0

    no-warn: 0

    pseudo-element: 0

    placeholder-in-extend: 0

    placeholder-name-format:
        - 1
        - allow-leading-underscore: true
          convention: '[a-z]+([-_].+)?'

    property-sort-order:
        - 1
        - ignore-custom-properties: true

    space-around-operator: 0

    space-before-colon: 0

    quotes:
        - 1
        - style: double

    variable-name-format:
        - 1
        - allow-leading-underscore: true
          convention: '[a-z]+([-_].+)?'
```
