### ISSUE TITLE
nothing happens when running sass-lint-auto-fix

### ISSUE THREAD

**Issue by davincif** [srowhani/sass-lint-auto-fix#286]
## Problem Description

After configure the project, sass-lint is working just fine but when I run sass-lint-auto-fix nothing works. Nothing at all, not even an error msg.
I feel like I'm missing something, so I'm not really sure if this is a bug report or a question, but it do is pretty wierd.

## Screenshot

Seriously, no neeed, nothing happens, but here is it:
![Captura de tela de 2020-05-30 18-57-06](https://user-images.githubusercontent.com/6793089/83339856-062c6680-a2a8-11ea-9a7b-1da813dc187f.png)

## Steps to recreate
First of all, the version I'm using is:
```json
{
  "sass-lint": "^1.13.1",
  "sass-lint-auto-fix": "^0.21.0"
}
```

create a src/index.css on the project folder with:
```css
body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  border: none;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  margin: 0;
}

code {
  font-family: source-code-pro,
    Menlo,
    Monaco,
    Consolas,
    'Courier New',
    monospace;
}
```

here is my sass-lint.yml file
```yml
files:
  include:
  - 'src/**/*.css'
  - 'public/**/*.css'
  ignore:
  - './src/assets/**'
  - './node_modules/**'
  - './docs/**'
  - './trash/**'

# sass-lint-auto-fix
resolvers:
  property-sort-order: 1
  attribute-quotes: 1
  border-zero: 1
  no-color-keywords: 1
  no-css-comments: 0
  no-important: 0
  no-trailing-zero: 1
  space-after-bang: 1
  space-before-bang: 1
  space-after-colon: 1
  space-before-colon: 1
  hex-length: 1
  empty-line-between-blocks: 1
  url-quotes: 1
  zero-unit: 1
  hex-notation: 1
  indentation: 0
  final-newline: 1
options:
  optOut: false

# add found here: https://github.com/airbnb/css/blob/master/.scss-lint.yml
severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes
```
and then run `npx sass-lint-auto-fix`, nothing happens the file index.css

Many Thanks, Leonardo Da Vinci.
