### ISSUE TITLE
Files that don't satisfy the 'include' conditions specified in the configuration file are also linted

### ISSUE THREAD

**Issue by abryant710** [srowhani/sass-lint-auto-fix#367]
## Problem Description

.sass-lint.yml file configuration to include certain files is not being respected

Versions:

```
"sass-lint": "^1.13.1",
"sass-lint-auto-fix": "^0.21.2",

```

Config:

```
files:
  include: 'app/javascript/styles/**/*.s+(a|c)ss'
resolvers:
  property-sort-order: 1
  attribute-quotes: 1
  border-zero: 1
  no-color-keywords: 1
  no-css-comments: 0
  no-important: 0
  no-trailing-zero: 1
  space-after-bang: 1
  space-before-bang: 1
  space-after-colon: 1
  space-before-colon: 1
  hex-length: 1
  empty-line-between-blocks: 1
  url-quotes: 1
  zero-unit: 1
  hex-notation: 1
  indentation: 0
  final-newline: 1
options:
  optOut: false
```

NPM script:

`"lint:css": "sass-lint-auto-fix --config-sass-lint .sass-lint.yml"`

## Screenshot

Before running script:

![Before](https://i.imgur.com/xCG6Xl9.png)

After running script:

![After](https://i.imgur.com/d7UWfk2.png)

## Steps to recreate

Add `.sass-lint.yml` to the root of the project, install npm packages listed, run npm script to auto fix the sass problems. The script captures files that don't satisfy the 'include' conditions specified in the configuration file.
