### ISSUE TITLE
`files.ignore` does not work

### ISSUE THREAD

**Issue by kinyat** [srowhani/sass-lint-auto-fix#4]
## Problem Description
Giving the following config

```yaml
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    # Too Cleanup
    - 'src/sass/**/*.s+(a|c)ss'
```

It still check the sass folder.
I then tried with the following.

```yaml
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore: random
```

No error is thrown. Seems like this setting does not work at all

## Screenshot

Part of the output showing that it is still include the excluded files
![image](https://user-images.githubusercontent.com/1476974/38842043-de38acb8-422a-11e8-95bc-c3a639657e18.png)

## Steps to recreate

- Use `ignore` to ignore some files
- run fix
