### ISSUE TITLE
empty-line-between-blocks doesn't fix all cases

### ISSUE THREAD

**Issue by srowhani** [srowhani/sass-lint-auto-fix#51]
This
```scss
.foo + .bar {
  content: 'foo';
}
.foo + .bar,
h2 {
  content: 'foo';
}
```

should result in

```scss
.foo + .bar {
  content: 'foo';
}

.foo + .bar,
h2 {
  content: 'foo';
}
```
