### ISSUE TITLE
more property-sort-order rules?

### ISSUE THREAD

**Issue by hibikikudo** [srowhani/sass-lint-auto-fix#60]
## I need some more property-sort-order rules
sass-lint-auto-fix fixes property-sort-order by alphabetical sequence by default.
could you arrange the option to be able to choose "concentric", "smacss" and  "recess" like following.

```
resolvers:
  property-sort-order: "smacss"
```
or 

```
  property-sort-order: 
    enabled: true
    order:
        - content
        - position
        - top
        - right
        ...
```

Thank you for your development Anyway!
