### ISSUE TITLE
Border-zero resolver is buggy

### ISSUE THREAD

**Issue by bivainis** [srowhani/sass-lint-auto-fix#88]
## Problem Description

Wen enabled, `border-zero` resolver does not account for integer value in `sass-lint.yml`
The resolver will only work if we provide a string instead of integer here (i. e. `'0'`).

If, on the other hand, integer value is provided, the program will write `border: ;` to the file (just an empty space instead of `border: 0;`.
```yml
# sass-lint.yml
rules:
  border-zero:
    - 2
    -
      convention: 0 # <-- notice integer value instead of string
```
